### ISSUE TITLE
Ice discussion 

### ISSUE THREAD

**Issue by milvinae** [hydrogen-dev/hydro-docs#19]
Will there be a size limit to documents that that Hydro app can process and create? 

Contracts are generally a small text based document so should be fine, however they may be packaged with reports that contain images etc that can run into hundreds of mb that also need stamping.

Will the app be able to handle stamping and creating two documents this size?

Would someone need to move the stamping functionally into a pdf creator which can be linked to the Hydro app?

Update 30.7.18

Whilst it would be recommended to upload an entire document to entire ensure a watertight stamping system, uploading large documents to the blockchain would, in most cases, be cost prohibitive.

For larger and/or less sensitive documents, including audio and video, would it be possible to build a system for watermarking a document, with the watermark then being documented by Ice.

I'm thinking along the lines of the coded copy protection added to movies that don't actually prevent copies, but show where that copy of the movie actually came from via a pattern of dots used as a forensic marker. With the right bit of software you could then compare the 'dots' on your file rather than the entire file.

Surely storing this dot data, or similar, on the chain would be a lot smaller than a large file and could give some confidence that the file you have is the correct one. Basically a lower level of document stamping.

**Comment by heavysunnyz** [comment]
Yes good
