### ISSUE TITLE
Ice whitepaper comments on behalf of 125fanger on Telegram

### ISSUE THREAD

**Issue by milvinae** [hydrogen-dev/hydro-docs#9]
Mike and & Co, ive just looked through the ICE whitepaper- elements of this appears to be very similar to what Docusign already does? How do you propose to integrate the audit functionality within ICE? Are there plans to create some sort of plugin to existing major ERP systems such as SAP, Oracle, Fiserv etc so that clients can quickly and easily interact with the blockchain? I think ease of use will be one of the biggest barriers to adoption. My clients at work would almost certainly use ICE if it was compatible with their existing ERP system. There is a project called Request Network (REQ) which is trying to do this plugin as well...may be worth a look.

Important to mention that REQ plans to implement a triple entry type of accounting record...may also be worth looking into. I am an Accountant and i dont have faith that REQ will succeed purely based on experience but i feel the Hydro team can. Also the advisory fee prize from the Luxembourg award with KPMG could be put to good use in this aspect. Appreciate its only $10k but perhaps there is also scope for our community to donate funds to get the advice needed. Alternatively, i am London based and work for one of the Big4 firms and would be happy to put Mike and the team in touch with one of our Partners here...we have several very very large clients who we are helping with blockchain implementation in their existing business

Also, mike, one of my mates is the founder of COOPEX, a new exchange being launched soon. He will contact your team to have hydro listed.

**Comment by movingforward4life** [comment]
Great Job!
